# Generated by Django 5.2.6 on 2025-09-16 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attributes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Hace referencia al nombre de la tarea', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Hace referencia a la descripcion de la tarea', max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('status_task', models.ForeignKey(help_text='Hace referencia al estado de la tarea.', on_delete=django.db.models.deletion.CASCADE, to='attributes.attribute')),
                ('user', models.ForeignKey(help_text='Hace referencia al id del usuario.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Task',
                'default_permissions': (),
            },
        ),
    ]
