# Generated by Django 5.2.6 on 2025-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('image', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('parent_user', models.PositiveBigIntegerField(null=True)),
                ('password_generated_by_api', models.IntegerField(blank=True, default=0, help_text='Hace referencia al cambio de contraseña o otros')),
                ('status', models.BooleanField(default=True)),
                ('creation_user', models.PositiveBigIntegerField(null=True)),
                ('user_update', models.PositiveBigIntegerField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'default_permissions': (),
            },
        ),
    ]
