# Generated by Django 5.2.6 on 2025-09-16 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hace referencia al nombre del parametro.', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Parameter',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hace referencia al nombre del parametro.', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('paramter', models.ForeignKey(blank=True, help_text='Hace referencia al id del paramtro.', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.parameter')),
            ],
            options={
                'db_table': 'Attribute',
                'default_permissions': (),
            },
        ),
    ]
