# Generated by Django 5.2.6 on 2025-09-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table='Attributes',
        ),
        migrations.AlterModelTable(
            name='parameter',
            table='Parameters',
        ),
    ]
